// THIS IS AN AUTOGENERATED FILE BY CREATE-WEB3-DAPP

export type CW3DConfig = {
	mainnetName: string;
	mainnetChainId: number;
	testnetChainId: number;
	testnetChainName: string;
};

const config = {
	mainnetName: "opt-mainnet",
	mainnetChainId: 10,
	testnetChainId: 11155420,
	testnetChainName: "opt-sepolia",
} as const satisfies CW3DConfig;

export default config; 