package integercontainer

import (
	"github.com/stretchr/testify/require"
	"testing"
)

// The test class below can be considered as a playground - feel free to modify it as you need, e.g.:
// - add your own custom tests
// - delete existing tests
// - modify test contents or expected output
//
// The results of tests from this file will always be at the beginning of the report generated by clicking the "Run" button.
//
// The results of these tests do not affect the final score (unless the project fails to build).
func TestSandbox(t *testing.T) {

	var container IntegerContainer

	t.Run("test sample", func(t *testing.T) {
		container = NewIntegerContainerImpl()
		require.Equal(t, 1, container.Add(5))
		require.Equal(t, 2, container.Add(10))
		require.Equal(t, 3, container.Add(5))
		require.True(t, container.Delete(10))
		require.False(t, container.Delete(1))
		require.Equal(t, 3, container.Add(1))
	})
}
