package integercontainer

import (
	"github.com/stretchr/testify/require"
	"testing"
)

// The test class below includes 10 tests for Level 2.
//
// All have the same score.
// You are not allowed to modify this file, but feel free to read the source code to better understand what is happening in every specific case.
func TestLevel2(t *testing.T) {

	var container IntegerContainer

	t.Run("test level 2 case 01 simple median odd length", func(t *testing.T) {
		container = NewIntegerContainerImpl()
		require.Equal(t, 1, container.Add(1))
		require.Equal(t, 2, container.Add(2))
		require.Equal(t, 3, container.Add(5))
		require.Equal(t, 4, container.Add(7))
		require.Equal(t, 5, container.Add(9))
		require.Equal(t, 5, *container.GetMedian())
		require.Equal(t, 6, container.Add(11))
		require.Equal(t, 7, container.Add(15))
		require.Equal(t, 7, *container.GetMedian())
	})

	t.Run("test level 2 case 02 simple median even length", func(t *testing.T) {
		container = NewIntegerContainerImpl()
		require.Equal(t, 1, container.Add(10))
		require.Equal(t, 2, container.Add(20))
		require.Equal(t, 10, *container.GetMedian())
		require.Equal(t, 3, container.Add(30))
		require.Equal(t, 4, container.Add(40))
		require.Equal(t, 20, *container.GetMedian())
		require.Equal(t, 20, *container.GetMedian())
		require.Equal(t, 5, container.Add(50))
		require.Equal(t, 6, container.Add(60))
		require.Equal(t, 7, container.Add(70))
		require.Equal(t, 8, container.Add(80))
		require.Equal(t, 40, *container.GetMedian())
	})

	t.Run("test level 2 case 03 median of empty container", func(t *testing.T) {
		container = NewIntegerContainerImpl()
		require.Nil(t, container.GetMedian())
		require.Equal(t, 1, container.Add(1))
		require.Equal(t, 1, *container.GetMedian())
	})

	t.Run("test level 2 case 04 median of non sorted container", func(t *testing.T) {
		container = NewIntegerContainerImpl()
		require.Equal(t, 1, container.Add(3))
		require.Equal(t, 2, container.Add(2))
		require.Equal(t, 3, container.Add(5))
		require.Equal(t, 4, container.Add(4))
		require.Equal(t, 5, container.Add(1))
		require.Equal(t, 3, *container.GetMedian())
		require.Equal(t, 6, container.Add(8))
		require.Equal(t, 7, container.Add(6))
		require.Equal(t, 8, container.Add(7))
		require.Equal(t, 4, *container.GetMedian())
	})

	t.Run("test level 2 case 05 median of container with duplicates", func(t *testing.T) {
		container = NewIntegerContainerImpl()
		require.Equal(t, 1, container.Add(5))
		require.Equal(t, 2, container.Add(3))
		require.Equal(t, 3, container.Add(5))
		require.Equal(t, 4, container.Add(5))
		require.Equal(t, 5, container.Add(10))
		require.Equal(t, 6, container.Add(3))
		require.Equal(t, 5, *container.GetMedian())
		require.Equal(t, 7, container.Add(3))
		require.Equal(t, 8, container.Add(3))
		require.Equal(t, 9, container.Add(3))
		require.Equal(t, 3, *container.GetMedian())
	})

	t.Run("test level 2 case 06 median with deletions", func(t *testing.T) {
		container = NewIntegerContainerImpl()
		require.Equal(t, 1, container.Add(30))
		require.Equal(t, 2, container.Add(20))
		require.Equal(t, 3, container.Add(10))
		require.Equal(t, 20, *container.GetMedian())
		require.True(t, container.Delete(30))
		require.Equal(t, 10, *container.GetMedian())
		require.True(t, container.Delete(10))
		require.Equal(t, 20, *container.GetMedian())
		require.True(t, container.Delete(20))
		require.Nil(t, container.GetMedian())
	})

	t.Run("test level 2 case 07 double median and deletions", func(t *testing.T) {
		container = NewIntegerContainerImpl()
		require.Nil(t, container.GetMedian())
		require.Nil(t, container.GetMedian())
		require.False(t, container.Delete(239))
		require.Nil(t, container.GetMedian())
		require.Nil(t, container.GetMedian())
		require.Equal(t, 1, container.Add(239))
		require.Equal(t, 239, *container.GetMedian())
		require.Equal(t, 239, *container.GetMedian())
		require.True(t, container.Delete(239))
		require.False(t, container.Delete(239))
		require.Nil(t, container.GetMedian())
		require.Nil(t, container.GetMedian())
	})

	t.Run("test level 2 case 08 median of container with negative integers", func(t *testing.T) {
		container = NewIntegerContainerImpl()
		require.Equal(t, 1, container.Add(-20))
		require.Equal(t, 2, container.Add(-10))
		require.Equal(t, 3, container.Add(10))
		require.Equal(t, 4, container.Add(20))
		require.Equal(t, 5, container.Add(0))
		require.Equal(t, 0, *container.GetMedian())
		require.Equal(t, 6, container.Add(-30))
		require.Equal(t, -10, *container.GetMedian())
		require.Equal(t, 7, container.Add(30))
		require.Equal(t, 0, *container.GetMedian())
		require.Equal(t, 8, container.Add(40))
		require.Equal(t, 9, container.Add(50))
		require.Equal(t, 10, *container.GetMedian())
	})

	t.Run("test level 2 case 09 mixed operations 1", func(t *testing.T) {
		container = NewIntegerContainerImpl()
		require.Nil(t, container.GetMedian())
		require.Equal(t, 1, container.Add(5))
		require.Equal(t, 2, container.Add(3))
		require.Equal(t, 3, container.Add(5))
		require.Equal(t, 4, container.Add(7))
		require.Equal(t, 5, container.Add(8))
		require.Equal(t, 6, container.Add(9))
		require.Equal(t, 5, *container.GetMedian())
		require.True(t, container.Delete(5))
		require.True(t, container.Delete(8))
		require.Equal(t, 5, *container.GetMedian())
		require.True(t, container.Delete(5))
		require.False(t, container.Delete(5))
		require.Equal(t, 7, *container.GetMedian())
		require.Equal(t, 4, container.Add(5))
		require.Equal(t, 5, *container.GetMedian())
		require.True(t, container.Delete(5))
		require.False(t, container.Delete(5))
		require.True(t, container.Delete(7))
		require.True(t, container.Delete(3))
		require.Equal(t, 9, *container.GetMedian())
		require.True(t, container.Delete(9))
		require.Nil(t, container.GetMedian())
		require.False(t, container.Delete(9))
		require.Nil(t, container.GetMedian())
	})

	t.Run("test level 2 case 10 mixed operations 2", func(t *testing.T) {
		container = NewIntegerContainerImpl()
		require.Nil(t, container.GetMedian())
		require.Equal(t, 1, container.Add(1))
		require.Equal(t, 2, container.Add(1))
		require.Equal(t, 3, container.Add(2))
		require.Equal(t, 4, container.Add(2))
		require.Equal(t, 5, container.Add(3))
		require.Equal(t, 6, container.Add(3))
		require.Equal(t, 7, container.Add(4))
		require.Equal(t, 8, container.Add(4))
		require.Equal(t, 9, container.Add(5))
		require.Equal(t, 10, container.Add(5))
		require.Equal(t, 3, *container.GetMedian())
		require.True(t, container.Delete(1))
		require.True(t, container.Delete(1))
		require.False(t, container.Delete(1))
		require.Equal(t, 3, *container.GetMedian())
		require.True(t, container.Delete(2))
		require.True(t, container.Delete(2))
		require.False(t, container.Delete(2))
		require.Equal(t, 4, *container.GetMedian())
		require.True(t, container.Delete(3))
		require.True(t, container.Delete(4))
		require.True(t, container.Delete(5))
		require.Equal(t, 4, *container.GetMedian())
	})
}
