// THIS IS AN AUTOGENERATED FILE BY CREATE-WEB3-DAPP

export type CW3DConfig = {
	mainnetName: string;
	mainnetChainId: number;
	testnetChainId: number;
	testnetChainName: string;
};

const config = {
	mainnetName: "eth-mainnet",
	mainnetChainId: 1,
	testnetChainId: 11155111,
	testnetChainName: "eth-sepolia",
} as const satisfies CW3DConfig;

export default config; 